server:
  port: 8081

spring:
  application:
    name: admin-service

  config:
    import:
      - optional:file:.env[.properties]
      - optional:app/mybatis/mybatis.yml
      - optional:app/jpa/jpa.yml
      - optional:app/consul/consul.yml
      - optional:app/jasypt/jasypt.yml
      - optional:app/cors/cors.yml
      - optional:app/jwt/jwt.yml

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${AUTH_POSTGRES_URL}
    username: ${AUTH_POSTGRES_USERNAME}
    password: ${AUTH_POSTGRES_PASSWORD}
    hikari:
      connectionTimeout: 30_000
      idleTimeout: 600_000
      maximum-pool-size: 300
      minimum-idle: 5
      maxLifetime: 30_000
      leak-detection-threshold: 2000

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:/db/migration # (default)

logging:
  level:
    root: debug
